include: package:flutter_lints/flutter.yaml

analyzer:
  #errors:
    #invalid_annotation_target: ignore

  exclude:
    - "lib/data/model/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true
    require_trailing_commas: true
    always_put_required_named_parameters_first: true