arb-dir: assets\l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false

output-class: GalleryLocalizations
preferred-supported-locales:
  - en
use-deferred-loading: false